# Foundations of Computational Economics #47

by Fedor Iskhakov, ANU

<img src="_static/img/dag3logo.png" style="width:256px;">

## Example exam questions

<img src="_static/img/lecture.png" style="width:64px;">

<img src="_static/img/youtube.png" style="width:65px;">

[https://youtu.be/zmxxyNsyTGI](https://youtu.be/zmxxyNsyTGI)

Description: Examples of questions and answers in the exam.

### Instructions: (from last year’s exam)

- Complete the tasks listed in this Jupyter notebook by answering
  questions and writing the code in the cell provided  
- Each task has a number of points associated with it, the complete
  exam assignment has 100 points  
- The grade is the total number of points earned  
- Started but not completed tasks, as well as task completed with
  errors earn partial points  
- You have 180 minutes to compete the exam  
- **Make sure to commit your work to Git and push the changes to GitHub for grading** (alternative ways to submit your exam may have been set on individual bases)  

#### Overall structure (last year)

- five 2 point questions (10 points)  
- ten 3 point questions (30 points)  
- four 5 point questions (20 points)  
- four 10 point questions (40 points)  

#### Types of questions/tasks

- 2 point and 3 points: elementary and simple questions which require short answer and check the knowledge of some simple facts  
- 5 points: more elaborate questions, short coding tasks, find-a-bug questions  
- 10 points: more elaborate coding tasks, very hard on their own, but doable with good knowledge and understanding of the code base developed in the course (so that useful donor code can be copied in quickly)  

#### Question 1. (2 points)

In Python code when assigning a value to a variable, how many spaces
should be used around the “=” sign according to PEP8?

#### Question 2. (2 points)

How does convergence rate of the value function iterations (successive
approximation) algorithm depend on the discount coefficient
$ \beta $?

#### Question 3. (3 points)

In NumPy what arithmetic operations differ between the two-dimensional
array type and the matrix type variables?

In [1]:
import numpy as np
a = np.array([[1,2,3],[0,3,5],[7,4,1]])
b = np.matrix([[1,2,3],[0,3,5],[7,4,1]])
print(a+a,b+b,sep='\n',end='\n\n')
print(a-a,b-b,sep='\n',end='\n\n')
print(a*a,b*b,sep='\n',end='\n\n')
print(a/a,b/b,sep='\n',end='\n\n')
print(a@a,b@b,sep='\n',end='\n\n')

[[ 2  4  6]
 [ 0  6 10]
 [14  8  2]]
[[ 2  4  6]
 [ 0  6 10]
 [14  8  2]]

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[ 1  4  9]
 [ 0  9 25]
 [49 16  1]]
[[22 20 16]
 [35 29 20]
 [14 30 42]]

[[ 1.  1.  1.]
 [nan  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  1.  1.]
 [nan  1.  1.]
 [ 1.  1.  1.]]

[[22 20 16]
 [35 29 20]
 [14 30 42]]
[[22 20 16]
 [35 29 20]
 [14 30 42]]



/usr/local/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in true_divide
  import sys


#### Question 4. (3 points)

Write the Bellman equation for the infinite horizon formulations of
the following problem:

- choice variable $ c $  
- state variables $ x,y,z $  
- $ x $ and $ y $ evolve stochastically with transition densities $ f_x(x',x,c) $ and $ f_y(y',x,y) $  
- instantaneous utility is given by $ u(c,y) $  
- motion rule for variable $ z $ can be left unspecified in the Bellman equation  

$$
V(x,y,z) = \max_{c}  \big[ U(c,y) + \beta \int\int V(x',y',z') f_y(y',x,y) f_x(x',x,c) dy' dx' \big]
$$

#### Question 5. (5 points)

Write a list comprehension expression to produce pairs of squares and
cubes of all integers between 1 to 10 inclusive.

In [2]:
squares_and_cubs = [(x**2,x**3) for x in range(1,11)]
print(squares_and_cubs)

[(1, 1), (4, 8), (9, 27), (16, 64), (25, 125), (36, 216), (49, 343), (64, 512), (81, 729), (100, 1000)]


#### Question 6. (5 points)

The code below outputs a negative value. This is strange because it
calculates an average of the powers of 2, which are all positive
numbers. Explain what is going on and fix the bug with *minimal change to
the code*.

In [3]:
import numpy as np
a = 2**np.arange(100)
print(a.mean())

-2.56


#### Question 7. (10 points)

Derive **your own algorithm** and implement it in a function that takes
an integer decimal number and outputs its binary representation. Write
your code in the cell below and run the test cases.

In [4]:
def binary(x):
    '''Input: integer in decimal, output: vector of 0 and 1 to represent the input in binary'''
    # write your code here
    return []

print(binary(1))
print(binary(2))
print(binary(3))
print(binary(4))
print(binary(1673))
print(binary(3428))

[]
[]
[]
[]
[]
[]


In [5]:
def binary(x):
    '''Input: integer in decimal, output: vector of 0 and 1 to represent the input in binary'''
    d = []
    while True:
        d.append(x%2)
        x//=2
        if x==0:
            return d[::-1]

for i in range(32):
    print(i,binary(i),sep=' = ')

print(binary(1))
print(binary(2))
print(binary(3))
print(binary(4))
print(binary(1673))
print(binary(3428))

0 = [0]
1 = [1]
2 = [1, 0]
3 = [1, 1]
4 = [1, 0, 0]
5 = [1, 0, 1]
6 = [1, 1, 0]
7 = [1, 1, 1]
8 = [1, 0, 0, 0]
9 = [1, 0, 0, 1]
10 = [1, 0, 1, 0]
11 = [1, 0, 1, 1]
12 = [1, 1, 0, 0]
13 = [1, 1, 0, 1]
14 = [1, 1, 1, 0]
15 = [1, 1, 1, 1]
16 = [1, 0, 0, 0, 0]
17 = [1, 0, 0, 0, 1]
18 = [1, 0, 0, 1, 0]
19 = [1, 0, 0, 1, 1]
20 = [1, 0, 1, 0, 0]
21 = [1, 0, 1, 0, 1]
22 = [1, 0, 1, 1, 0]
23 = [1, 0, 1, 1, 1]
24 = [1, 1, 0, 0, 0]
25 = [1, 1, 0, 0, 1]
26 = [1, 1, 0, 1, 0]
27 = [1, 1, 0, 1, 1]
28 = [1, 1, 1, 0, 0]
29 = [1, 1, 1, 0, 1]
30 = [1, 1, 1, 1, 0]
31 = [1, 1, 1, 1, 1]
[1]
[1, 0]
[1, 1]
[1, 0, 0]
[1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1]
[1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0]


#### Question 8. (10 points)

Consider the consumption/savings problem in the infinite horizon. Each
period the agent chooses how much to consume from the cash-in-hand
$ M_t $ (without borrowing). The amount remaining after consumption
grows stochastically with the gross return taking one of five values
presented in the table below (independently distributed across time). In
addition, each period the agent receives a non-stochastic government
support payment of \$10 (in thousands). Return on savings and the latter
payment are the only sources of income.

The instantaneous utility of consumption is given by
$ u(C_t)=\log(C_t) $.

Stochastic gross returns on savings are given by

|R|0.85|0.95|1.05|1.10|1.40|
|:-:|:----:|:----:|:----:|:----:|:----:|
|p|0.05|0.20|0.55|0.15|0.05|
.

1. Write the Bellman equation for the problem.  
1. Write the code to solve the problem and plot the value function and
  the optimal policy function, assuming that the choices are made on a
  discrete grid with step \$1, and the upper bound of the problem is set
  to \$200.  